#!/bin/sh
# Regenerates the Homebrew formula and the Scoop manifest for one release from
# the SHA256SUMS that release published. Run after every release:
#
#   ./scripts/update-packaging.sh 0.1.0
#
# The two files under packaging/ are generated; edit this script, not them.
# The Homebrew formula is meant to be copied verbatim to Formula/clift.rb in the
# leazoot/homebrew-clift tap.

set -eu

repo="leazoot/clift"
version="${1:?usage: $0 <version, e.g. 0.1.0>}"
version="${version#v}"
release="https://github.com/${repo}/releases/download/v${version}"

here="$(cd "$(dirname "$0")/.." && pwd)"
sums="$(mktemp)"
trap 'rm -f "$sums"' EXIT

curl -fsSL -o "$sums" "${release}/SHA256SUMS"

# digest <archive name>: the hex in front of exactly that name, whether the line
# was written as "<hex>  <name>" or "<hex> *<name>".
digest() {
    found="$(awk -v name="$1" '
        { line = $0; sub(/^[0-9a-fA-F]+[ \t]+\*?/, "", line); if (line == name) { print $1; exit } }
    ' "$sums")"
    [ -n "$found" ] || { echo "SHA256SUMS for v${version} does not list $1" >&2; exit 1; }
    printf '%s' "$found"
}

mac_arm="$(digest "clift-${version}-aarch64-apple-darwin.tar.gz")"
mac_intel="$(digest "clift-${version}-x86_64-apple-darwin.tar.gz")"
# Linux archives are static musl; fall back to a glibc archive only if a
# release lists no musl one.
linux_flavour() {
    if grep -q "clift-${version}-$1-unknown-linux-musl.tar.gz" "$sums"; then
        printf 'musl'
    else
        printf 'gnu'
    fi
}
linux_arm_flavour="$(linux_flavour aarch64)"
linux_intel_flavour="$(linux_flavour x86_64)"
linux_arm="$(digest "clift-${version}-aarch64-unknown-linux-${linux_arm_flavour}.tar.gz")"
linux_intel="$(digest "clift-${version}-x86_64-unknown-linux-${linux_intel_flavour}.tar.gz")"
windows="$(digest "clift-${version}-x86_64-pc-windows-msvc.zip")"

# Both files are generated, so the directories holding them need not exist
# beforehand: after a release that published none, this script is what puts
# them back.
mkdir -p "${here}/packaging/homebrew" "${here}/packaging/scoop"

cat > "${here}/packaging/homebrew/clift.rb" <<RUBY
# Generated by scripts/update-packaging.sh for v${version}; do not edit by hand.
class Clift < Formula
  desc "Paste a screenshot into the coding agent running on your server"
  homepage "https://github.com/${repo}"
  version "${version}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "${release}/clift-${version}-aarch64-apple-darwin.tar.gz"
      sha256 "${mac_arm}"
    end
    on_intel do
      url "${release}/clift-${version}-x86_64-apple-darwin.tar.gz"
      sha256 "${mac_intel}"
    end
  end

  on_linux do
    on_arm do
      url "${release}/clift-${version}-aarch64-unknown-linux-${linux_arm_flavour}.tar.gz"
      sha256 "${linux_arm}"
    end
    on_intel do
      url "${release}/clift-${version}-x86_64-unknown-linux-${linux_intel_flavour}.tar.gz"
      sha256 "${linux_intel}"
    end
  end

  def install
    bin.install "clift"
    bin.install "clift-relayd"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/clift --version")
  end
end
RUBY

cat > "${here}/packaging/scoop/clift.json" <<JSON
{
  "version": "${version}",
  "description": "Paste a screenshot into the coding agent running on your server",
  "homepage": "https://github.com/${repo}",
  "license": "Apache-2.0",
  "architecture": {
    "64bit": {
      "url": "${release}/clift-${version}-x86_64-pc-windows-msvc.zip",
      "hash": "${windows}",
      "extract_dir": "clift-${version}-x86_64-pc-windows-msvc"
    }
  },
  "bin": [
    "clift.exe",
    "clift-relayd.exe"
  ],
  "checkver": "github",
  "autoupdate": {
    "architecture": {
      "64bit": {
        "url": "https://github.com/${repo}/releases/download/v\$version/clift-\$version-x86_64-pc-windows-msvc.zip",
        "extract_dir": "clift-\$version-x86_64-pc-windows-msvc"
      }
    },
    "hash": {
      "url": "\$baseurl/SHA256SUMS"
    }
  }
}
JSON

echo "wrote packaging/homebrew/clift.rb and packaging/scoop/clift.json for v${version}"
