# Generated by scripts/update-packaging.sh for v0.1.1; do not edit by hand.
class Clift < Formula
  desc "Paste a screenshot into the coding agent running on your server"
  homepage "https://github.com/leazoot/clift"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/leazoot/clift/releases/download/v0.1.1/clift-0.1.1-aarch64-apple-darwin.tar.gz"
      sha256 "f227924edede3ccb7c4b5cd70dbb7789ce54bed311fd73505f4a27e8e4816c7b"
    end
    on_intel do
      url "https://github.com/leazoot/clift/releases/download/v0.1.1/clift-0.1.1-x86_64-apple-darwin.tar.gz"
      sha256 "396358263f40ee1a54ec29184f6743c544cad87db3a51280fdb0e488b41f123b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/leazoot/clift/releases/download/v0.1.1/clift-0.1.1-aarch64-unknown-linux-musl.tar.gz"
      sha256 "b4be21665c474d0b982491e2a8ea069fd51ae2a1995b7f138a6bb3c9e026cb1b"
    end
    on_intel do
      url "https://github.com/leazoot/clift/releases/download/v0.1.1/clift-0.1.1-x86_64-unknown-linux-musl.tar.gz"
      sha256 "6834d3f87e9086e1f1486751cf89e59ea28c7db3b9a1749f7646881cd0d7ae21"
    end
  end

  def install
    bin.install "clift"
    bin.install "clift-relayd"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/clift --version")
  end
end
